name: Docker Nightly Image CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Name of the GitHub branch to create image off.'
        required: true
        default: 'master'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'nightly'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Amazon ECR Login Action for GitHub Actions
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/images/n8n-custom/Dockerfile
          platforms: linux/amd64
          push: true
          tags: public.ecr.aws/a5i1n5j8/stack9-n8n:${{ github.event.inputs.tag || 'nightly' }}
